//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GirlsAgency.SQLite.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class GirlsTax
    {
        public long id { get; set; }
        public string GirlName { get; set; }
        public int Tax { get; set; }
    }
}
